### ISSUE TITLE
SDK Obj-C headers lack Swift annotations

### ISSUE THREAD

**Issue by PatInANutshell** [TuneOSS/sdk-release#30]
Xcode will treat the lack of annotations as implicitly unwrapped optionals, which will cause exceptions if you pass in nil, which in many cases is a valid value for properties or arguments. It also forces calls to treat new instances as optional when they don't need to be.

**Comment by hasaudrey** [comment]
I think this is a dupe of https://github.com/TuneOSS/sdk-release/issues/27, or at least I hope to solve them both at the same time
