### ISSUE TITLE
Cant' build android sdk

### ISSUE THREAD

**Issue by anoreg** [TuneOSS/sdk-release#31]
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at android_release_aar_dulkhoq89m33wxqb89a5btma5.run(https://raw.githubusercontent.com/blundell/release-android-library/master/android-release-aar.gradle:43)
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'creates' not found in root project 'sdk-android'.

**Comment by john-gu** [comment]
Hi @anoreg, may I ask what's the gradle build command you're running?

**Comment by anoreg** [comment]
@john-gu 
./gradlew makeJar creates /dist/TuneMarketingConsoleSDK-x.y.z.jar
I'm using android stuido 2.3.1
compileSdkVersion 25
buildToolsVersion '25.0.2'
gradle 2.14.1
android plugin version 2.2.3

**Comment by john-gu** [comment]
Hi @anoreg, can you try running just:
`./gradlew makeJar`

I think you may be copying and running the entire line.

**Comment by anoreg** [comment]
@john-gu 
Great, the makeJar works
