### ISSUE TITLE
Tune doesn't compile for iOS devices in Xcode 9b3

### ISSUE THREAD

**Issue by marksvend** [TuneOSS/sdk-release#33]
I've had to comment out this Jailbreak check line to compile in iOS 11/Xcode 9:
https://github.com/TuneOSS/sdk-release/blob/master/sdk-ios/Tune/Tune/TuneUtils.m#L185

The int system(const char *) API has been marked __IOS_PROHIBITED

**Comment by hasryanr** [comment]
Hey @marksvend thanks for reaching out.  Our SDK Team is working to resolve iOS 11/Xcode 9 compatibility issues and hope to have a fix pushed out with the next SDK release.  If you have any additional questions or concerns do let us know.

**Comment by hasaudrey** [comment]
This is resolved.
