### ISSUE TITLE
 The class name and file name are not the same case, and a build error occurs.

### ISSUE THREAD

**Issue by coolsharp** [TuneOSS/sdk-release#36]
The class name and file name are not the same case, and a build error occurs.
https://github.com/TuneOSS/sdk-release/blob/master/sdk-android/TuneMarketingConsoleSDK/src/main/java/com/tune/smartwhere/TuneSmartWhereConfiguration.java

**Comment by atroutt** [comment]
Yikes! Sorry about that @coolsharp I just created a ticket for our team to fix that. We have non-case-sensitive file systems, so we didn't notice.

**Comment by tune-andyp** [comment]
Fixed SDK v5.2.2
