### ISSUE TITLE
SDK IOS 4.14.1 : Cannot convert value of type '[UIApplicationOpenURLOptionsKey : Any]' to expected argument type '[String : Any]!'

### ISSUE THREAD

**Issue by charliefancelli** [TuneOSS/sdk-release#40]
Hi,

Your SDK seem to be outdated from Apple native function (app in SWIFT 3.2)

```
func application(_ application: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    
   // When the app is opened due to a deep link, call the Tune deep link setter
    Tune.handleOpen(url, options: options)

return true
}
```

We have the issue : `Cannot convert value of type '[UIApplicationOpenURLOptionsKey : Any]' to expected argument type '[String : Any]!'` 

Can you update it or give us the documentation for this issue.

Regards,

**Comment by atroutt** [comment]
Hi Charlie,

We are aware of this and have it in the queue of fixes for the iOS SDK. The best I can offer right now is a workaround: 
```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    // Tune the API is mismatched from the iOS API, to be fixed by them in a later release
    // TEMPORARY: Convert keys from UIApplicationOpenURLOptionsKey -> String as workaround
    var newOptions: [String: Any] = [:]
    for (key, value) in options {
        newOptions[String(describing:key)] = value
    }
    Tune.handleOpen(url, options:newOptions)
    return true
}
```
-Audrey

**Comment by charliefancelli** [comment]
Hi Audrey,

Thanks for the reply, we thought about the fix but i prefered asking to you. 

We do that fix until you fix it directly in our SDK.

Regards,

**Comment by kevmalek** [comment]
Any word on a fix for this? We're implementing the workaround in the mean time. Thanks
