### ISSUE TITLE
Click Injection Issue

### ISSUE THREAD

**Issue by JSpiner** [TuneOSS/sdk-release#42]
I heard that Google and tune created a new referrer API to prevent click injection.([here](https://www.tune.com/blog/obliterating-click-injection-fraud-android/))
I think it is a good solution.
So, which sdk version does support this issue?

**Comment by atroutt** [comment]
Hi! The Tune Android SDK 4.15.0 release was the first to leverage the new API from Google Play. So, any version after that will include this functionality.

**Comment by JSpiner** [comment]
@atroutt 
Wow, that's great. 
Are there no backward compatibility issues?
I want to use the latest version as soon as possible. But I'm worried that it has been tested enough (because it's a completely new api)

**Comment by john-gu** [comment]
Hi @JSpiner, we still support the INSTALL_REFERRER intent receiver as a fallback solution for devices that have not updated to access the referrer API.
